use std::fs;
use std::io::{self, BufRead, Write};
use std::path::Path;
use std::process::Command;
use colored::Colorize;
use crate::env as cli_env;

pub fn run_tinker() -> Result<(), Box<dyn std::error::Error>> {
    cli_env::load_env()?;

    if !Path::new("Cargo.toml").exists() {
        return Err("Not inside a Cargo project. Run this command from your project root.".into());
    }

    let cargo_toml = fs::read_to_string("Cargo.toml")?;
    let crate_name = extract_crate_name(&cargo_toml)
        .ok_or("Could not determine crate name from Cargo.toml")?;
    let crate_ident = crate_name.replace('-', "_");

    fs::create_dir_all("src/bin")?;
    let tinker_path = Path::new("src/bin/_tinker.rs");

    println!("🧪 Oxidite Tinker v2.3.1");
    println!("Type Rust expressions to evaluate them in your project's context.");

    let stdin = io::stdin();
    let mut lines = stdin.lock().lines();

    loop {
        print!("oxidite> ");
        io::stdout().flush()?;

        let line = match lines.next() {
            Some(Ok(l)) => l,
            _ => break,
        };

        let trimmed = line.trim();
        if trimmed.is_empty() { continue; }
        if trimmed == "exit" || trimmed == "quit" { break; }

        let has_lib = Path::new("src/lib.rs").exists();

        let imports = if has_lib {
            format!("use {}::*;", crate_ident)
        } else {
            // Better error message for binary crates as requested in Option B
            println!("{}", "⚠️  Oxidite Tinker requires a library target (src/lib.rs) to pre-import your project's modules.".yellow());
            println!("You can still evaluate standard Rust expressions, but project-specific types won't be available unless you add a src/lib.rs.");
            String::new()
        };

        let code = format!(
            r#"// Auto-generated by `oxidite tinker`. Do not commit.
{}

#[tokio::main]
async fn main() {{
    let __result = {{ {} }};
    println!("{{:?}}", __result);
}}
"#,
            imports,
            trimmed,
        );

        fs::write(tinker_path, &code)?;

        print!("{}", "  ⚙️  Evaluating...".green());
        io::stdout().flush()?;

        let output = Command::new("cargo")
            .args(["run", "--bin", "_tinker", "--quiet"])
            .envs(std::env::vars()) // Ensure env vars are passed to tinker too
            .output();

        print!("\r\x1B[K");
        io::stdout().flush()?;

        match output {
            Ok(out) => {
                if !out.status.success() {
                    println!("{}", "  ❌ Evaluation failed:".red().bold());
                    eprintln!("{}", String::from_utf8_lossy(&out.stderr).red());
                } else {
                    io::stdout().write_all(&out.stdout)?;
                }
            }
            Err(e) => eprintln!("{}", format!("Failed to run snippet: {}", e).red()),
        }
    }

    if tinker_path.exists() {
        let _ = fs::remove_file(tinker_path);
    }

    println!("\n👋 Goodbye!");
    Ok(())
}

fn extract_crate_name(toml_content: &str) -> Option<String> {
    let mut in_package = false;
    for line in toml_content.lines() {
        let trimmed = line.trim();
        if trimmed == "[package]" { in_package = true; continue; }
        if trimmed.starts_with('[') { in_package = false; continue; }
        if in_package {
            if let Some(rest) = trimmed.strip_prefix("name") {
                let rest = rest.trim_start().strip_prefix('=').unwrap_or(rest).trim();
                return Some(rest.trim_matches('"').to_string());
            }
        }
    }
    None
}
